kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: ghcr.io/liquid-reply/kind-crun-wasm:v1.23.4
networking:
  disableDefaultCNI: true
  podSubnet: 10.244.0.0/16
